#!/usr/bin/ucode
// Walks docs/*.md, CLAUDE.md, README.md and .github/workflows/ci.yml and fails on a
// reference that does not resolve: a repo path that is not there, a `module.export` that
// the module does not export, a `make <target>` the Makefile does not define, and an error
// code documented as returned that nothing emits.
//
// It exists because four false documentation claims were found by hand in the space of a
// few days, each corrected individually with nothing to stop the next: a perf gate whose
// comparison file has never existed, a CI job claiming to prove byte-identical APKs while
// comparing no digests, a 415 documented as returned when Content-Type is never inspected,
// and `?confirm` described as minting concurrent windows an exclusive flock forbids. Two of
// those four are shapes this catches; the other two are not, see below.
//
// Patterns NOT detected, stated so the OK line is not read as more than it is:
//
//   - "This job proves X" where the job exists and does something adjacent. Both the perf
//     gate and verify-arch-build cited real artifacts, so no reference check reaches them.
//     Roughly 46 such claims exist and hand review is still the only instrument.
//   - Modal invariants: never, cannot, atomic, guarantees. Roughly 160 tokens.
//   - Line numbers. docs/lock-state-audit.md is the one place that cites ranges and about
//     seven have drifted; nothing here reads them.
//   - Prose that names a resource path (`network/interfaces`), a uci option or an absolute
//     runtime path (`/etc/config/dhcp`). Those are not repo files and are skipped by the
//     first-segment test below.
//
// It reads the working tree, not the index, so a build product sitting in a developer's
// checkout hides a stale reference to it until CI runs on a clean one. That is how the
// three `build/` waivers below were found: this passed locally and failed in CI. CI is the
// authoritative run for that reason.

import * as fs from 'fs';

// Keyed by the exact reference, value is the reason. A reference lands here when it is
// deliberately unresolvable, never to quiet a real break.
const WAIVERS = {
	"bench/baseline.json":
		"cited BECAUSE it does not exist: the perf bench measures and gates nothing without it",
	"tools/gen_changelog.sh":
		"named as a rejected alternative in the release process, not a file we ship",
	"bus.uci_get":
		"method on the object bus.connect() returns, not an export of bus.uc",
	"bus.uci_export":
		"method on the object bus.connect() returns, not an export of bus.uc",
	"unsupported_media_type":
		"documented as reserved and never returned; the check exists to catch the next one",
	"make defconfig":
		"a target of the OpenWrt SDK tree, not of this Makefile",
	"make package/uapi/compile":
		"built in the OpenWrt SDK tree by `make stage`, not a target of this Makefile",
	"make menuconfig":
		"a target of the OpenWrt SDK tree, not of this Makefile",
	"package/network/utils/wireguard-tools/files/wireguard.uc":
		"a path in the upstream OpenWrt tree, not in this repo",
	"build/sbom.spdx.json":
		"generated by `make sbom`; `make clean` removes it, so a clean checkout has none",
	"build/openwrt/uapi/files":
		"staged by `make stage`; `make clean` removes it",
	"build/sdk/feeds/luci/":
		"the OpenWrt SDK is downloaded by `make stage`, never committed",
};

function read(path) {
	let f = fs.open(path, "r");
	if (!f) return null;
	let raw = f.read("all") ?? "";
	f.close();
	return raw;
}

function exists(path) {
	try { return fs.stat(path) != null; } catch (e) { return false; }
}

// Everything the check reads. ci.yml is in scope because two of the four instances were
// comments in it rather than prose in docs/.
function corpus() {
	let out = [];
	let md = fs.lsdir("docs", "*.md") ?? [];
	sort(md);
	for (let f in md) push(out, "docs/" + f);
	for (let f in [ "CLAUDE.md", "README.md", "CONTRIBUTING.md",
	                ".github/workflows/ci.yml" ])
		if (exists(f)) push(out, f);
	return out;
}

let problems = [];
function report(file, lineno, what, detail) {
	push(problems, sprintf("  %s:%d  %s\n      %s", file, lineno, what, detail));
}

// Root entries decide what looks like a repo path at all, so `network/interfaces` (no such
// directory) is prose while `src/lib/values.uc` is a claim about a file.
let roots = {};
for (let e in fs.lsdir(".") ?? []) roots[e] = true;

let lib_exports = {};
for (let f in fs.lsdir("src/lib", "*.uc") ?? []) {
	let mod = substr(f, 0, length(f) - 3);
	let src = read("src/lib/" + f) ?? "";
	// The export block is the module's final `return { ... }`; coverage.uc parses it the
	// same way, which is why that block must stay brace-free.
	let m = match(src, /return[ \t\n]*\{([^}]*)\}[ \t\n]*;?[ \t\n]*$/);
	let names = {};
	if (m) for (let chunk in split(m[1], ",")) {
		let t = trim(chunk);
		if (t != "") names[split(t, ":")[0]] = true;
	}
	lib_exports[mod] = names;
}

let makefile = read("Makefile") ?? "";
let make_targets = {};
for (let line in split(makefile, "\n")) {
	let m = match(line, /^([A-Za-z][A-Za-z0-9_.\/-]*):/);
	if (m) make_targets[m[1]] = true;
}

// A suffix only means "file" if it is one we actually ship. Without this list,
// `firewall/zones.name` reads as a file called name and `handler.uc` reads as a module
// exporting `uc`.
const FILE_SUFFIX = /\.(uc|md|json|sh|yml|yaml|txt|pem|asc|conf|service|lock|sha256|gz|apk|adb)$/;

let counts = { paths: 0, symbols: 0, targets: 0 };

for (let file in corpus()) {
	let text = read(file);
	if (text == null) continue;
	let lines = split(text, "\n");
	for (let i = 0; i < length(lines); i++) {
		let line = lines[i];
		let ticked = match(line, /`([^`\n]+)`/g) ?? [];
		for (let t in ticked) {
			let ref = t[1];
			if (WAIVERS[ref] != null) continue;

			// A repo path: has a slash, is not absolute, not a URL, not a glob or
			// placeholder, and either starts at a real root entry or carries a suffix.
			if (index(ref, "/") >= 0 && substr(ref, 0, 1) != "/"
			    && index(ref, "://") < 0 && index(ref, "*") < 0
			    && index(ref, "<") < 0 && index(ref, " ") < 0
			    && index(ref, "#") < 0 && index(ref, ":") < 0) {
				let first = split(ref, "/")[0];
				let looks_like_file = match(ref, FILE_SUFFIX) != null;
				if (roots[first] || looks_like_file) {
					let bare = ref;
					if (substr(bare, length(bare) - 1) == "/")
						bare = substr(bare, 0, length(bare) - 1);
					counts.paths++;
					if (!exists(bare))
						report(file, i + 1, sprintf("path does not exist: %s", ref),
						       "Fix the path, or add it to WAIVERS with the reason it is cited while absent.");
				}
			}

			// A `module.export` claim, only for modules that actually exist under src/lib.
			let sym = (index(ref, "/") < 0 && match(ref, FILE_SUFFIX) == null)
			          ? match(ref, /^([a-z_][a-z0-9_]*)\.([a-z_][A-Za-z0-9_]*)$/) : null;
			if (sym && lib_exports[sym[1]] != null) {
				counts.symbols++;
				if (!lib_exports[sym[1]][sym[2]])
					report(file, i + 1,
					       sprintf("src/lib/%s.uc does not export %s", sym[1], sym[2]),
					       "Fix the symbol, or add it to WAIVERS if it is a method on a returned object rather than an export.");
			}
		}

		// Only backticked targets. The house style is `make lint`, whereas prose
		// ("make recovery infeasible") and the CI package list ("apk add make grep")
		// both contain the same two words and mean nothing of the kind. A blocklist of
		// English words would need extending forever; requiring the backticks does not.
		for (let t in match(line, /`make ([a-z][a-z0-9\/-]*)`/g) ?? []) {
			let target = t[1];
			if (WAIVERS["make " + target] != null) continue;
			counts.targets++;
			if (!make_targets[target])
				report(file, i + 1, sprintf("Makefile defines no target %J", target),
				       "Fix the target name, or add \"make <target>\" to WAIVERS if it belongs to another Makefile (an SDK tree, for instance).");
		}
	}
}

// Claims a doc attributes to a test. A doc that says what a test asserts is the shape that
// went wrong twice: "5 distinct PIDs" where the test asserted 2, and "asserted live" for a
// case only a unit test covers. The convention is that the test prints the claim beside its
// assertion and the doc quotes that string, which turns an unverifiable statement about
// behaviour into a reference that either resolves or does not.
let test_text = "";
for (let d in [ "tests/integration", "tests/unit" ]) {
	for (let f in fs.lsdir(d) ?? []) {
		if (index(f, "test") < 0) continue;
		test_text += read(d + "/" + f) ?? "";
	}
}
let claim_count = 0;
for (let file in corpus()) {
	let text = read(file);
	if (text == null) continue;
	let lines = split(text, "\n");
	for (let i = 0; i < length(lines); i++) {
		for (let m in match(lines[i], /claims "([^"]+)"/g) ?? []) {
			claim_count++;
			if (index(test_text, m[1]) < 0)
				report(file, i + 1,
				       sprintf("no test prints this claim: %J", m[1]),
				       "Quote the CLAIM line the test prints, or add the claim to the test beside the assertion it describes.");
		}
	}
}

// Announced deprecations must reach the published spec, not just the ledger. This exists
// because the list-reads-null change was recorded in docs/deprecations.md and in the
// changelog while appearing nowhere in build/openapi.json: a consumer generating a client
// got no signal at all that every array field's type changes in v3, which is the one
// notice most likely to break a generated client. The whole point of announcing in a minor
// is that the notice reaches the artifact people consume.
let dep_md = read("docs/deprecations.md") ?? "";
let spec_desc = "";
let spec_raw = read("build/openapi.json");
if (spec_raw != null) {
	let spec = json(spec_raw);
	spec_desc = ((spec ?? {}).info ?? {}).description ?? "";
}
let announced = 0;
for (let line in split(dep_md, "\n")) {
	// Active deprecation rows: | `<resource>.<field>` (...) | ... |
	let row = match(line, /^\|[ \t]*`([a-z_0-9]+\/[a-z_0-9]+\.[a-z_0-9]+)`/);
	if (row) {
		announced++;
		if (index(spec_desc, row[1]) < 0)
			report("docs/deprecations.md", 0,
			       sprintf("%s is announced in the ledger but not in the spec's own description", row[1]),
			       "Add it to the \"Upcoming in v3\" block in build/gen_openapi.uc, or the notice never reaches a generated client.");
	}
}
// Response-shape bullets are prose. Matching them by a backticked token looked tidy and
// would have been useless: the list-reads-null bullet, the one that was actually missing
// from the spec, does not start with a backtick. So the two sides are compared by count
// instead, which catches an item added to either place and not the other.
let shape_bullets = 0;
let in_shape = false;
for (let line in split(dep_md, "\n")) {
	if (index(line, "## Announced response-shape changes") == 0) { in_shape = true; continue; }
	if (in_shape && substr(line, 0, 3) == "## ") in_shape = false;
	if (in_shape && substr(line, 0, 4) == "- **") shape_bullets++;
}
announced += shape_bullets;

let spec_bullets = 0;
let in_upcoming = false;
for (let line in split(spec_desc, "\n")) {
	if (index(line, "## Upcoming in v3") == 0) { in_upcoming = true; continue; }
	if (in_upcoming && substr(line, 0, 3) == "## ") in_upcoming = false;
	if (in_upcoming && substr(line, 0, 4) == "- **") spec_bullets++;
}
if (spec_bullets != announced)
	report("docs/deprecations.md", 0,
	       sprintf("the ledger announces %d changes; the spec's \"Upcoming in v3\" block lists %d",
	               announced, spec_bullets),
	       "Every announcement has to reach build/openapi.json, or a generated client gets no notice. Edit the block in build/gen_openapi.uc and regenerate.");

// Error codes, both directions. A code documented as returned must be emitted somewhere,
// and a code in the published enum must be documented. The emit test is "the string
// appears in src/ outside errors.uc", because errors.uc holds the status and enum tables:
// the 415 claim survived a check that only looked for the string. It also has to be that
// loose, since the 401 codes are emitted as `errors.error(ctx, auth_result.kind, msg)`
// with the code in a variable.
let errors_md = read("docs/errors.md") ?? "";
let src_text = "";
for (let d in [ "src", "src/lib", "src/resources" ]) {
	for (let f in fs.lsdir(d, "*.uc") ?? []) {
		if (d == "src/lib" && f == "errors.uc") continue;
		src_text += read(d + "/" + f) ?? "";
	}
}

let doc_codes = {};
let code_count = 0;
let err_lines = split(errors_md, "\n");
for (let i = 0; i < length(err_lines); i++) {
	let m = match(err_lines[i], /^\|[ \t]*([0-9]{3})[ \t]*\|[ \t]*`([a-z_]+)`/);
	if (!m) continue;
	doc_codes[m[2]] = m[1];
	if (WAIVERS[m[2]] != null) continue;
	code_count++;
	if (index(src_text, m[2]) < 0)
		report("docs/errors.md", i + 1,
		       sprintf("%s %s is documented as returned but nothing in src/ emits it", m[1], m[2]),
		       "Emit it, document it as reserved, or add it to WAIVERS with that reason.");
}

let errors_uc = read("src/lib/errors.uc") ?? "";
let all_block = match(errors_uc, /const ALL_CODES = \[([^\]]*)\]/);
let enum_count = 0;
if (all_block) {
	let uc_lines = split(errors_uc, "\n");
	for (let q in match(all_block[1], /"([a-z_]+)"/g) ?? []) {
		enum_count++;
		if (doc_codes[q[1]] != null || index(errors_md, q[1]) >= 0) continue;
		let at = 0;
		for (let i = 0; i < length(uc_lines); i++)
			if (index(uc_lines[i], "\"" + q[1] + "\"") >= 0) { at = i + 1; break; }
		report("src/lib/errors.uc", at,
		       sprintf("%s is in the published ALL_CODES enum but appears nowhere in docs/errors.md", q[1]),
		       "Document it, or drop it from the enum.");
	}
}

if (length(problems) > 0) {
	printf("FAIL: %d documentation reference(s) do not resolve:\n\n", length(problems));
	for (let p in problems) print(p + "\n");
	printf("\nA reference that cannot resolve is a claim the tree does not support.\n");
	printf("Fix it, or document the exception in tests/lint_doc_refs.uc::WAIVERS.\n");
	exit(1);
}

printf("OK: %d paths, %d module exports, %d make targets, %d test claims, %d announced deprecations, %d documented codes, %d enum codes, all resolve\n",
       counts.paths, counts.symbols, counts.targets, claim_count, announced, code_count, enum_count);
